### ISSUE TITLE
Python-based implementation?

### ISSUE THREAD

**Issue by justanhduc** [tienthanhdhcn/Vietnamese-Accent-Prediction#1]
Hi there.
This project seems really cool and I would like to ask if there happens to be any implementation in Python. I have no experience in Java before.
Thank you.

**Comment by tienthanhdhcn** [comment]
Hi @justanhduc, thanks for your consideration. I don't have any plan for a Python implementation at the moment. However, if you do some search on Github, you can find some similar project implemented in python.
