### ISSUE TITLE
Ask ngram algorithm

### ISSUE THREAD

**Issue by manvan18** [tienthanhdhcn/Vietnamese-Accent-Prediction#2]
Can you talk me about nrgram algorithm you use?
if(number1GRam > 0 && number2GRam > 0) {
								log = Math.log((double) (number2GRam + 1) / (number1GRam + _1Statistic.get(_old)));
							}
							else log = Math.log(1.0 / (2*(size2Grams + totalcount2Grams)));
							
							if(i == 1) {
								log += Math.log((double)(number1GRam + 1)/(size1Gram + totalcount1Gram));
							}
Can you share me link about it? I can know it. I am a student and I am learnning it! Thanks you very much!

**Comment by tienthanhdhcn** [comment]
Hi @manvan18 

We used uni-gram(1-gram) and bi-grams (2-grams). For the Markov model,  we used Laplace smoothing to ensure that p is always greater than 0.

Before applying smoothing
- p(a|b) = bi_gram(ab)/uni_gram(b)
After applying smoothing
- p(a|b) = (bi_gram(ab) + 1)/(uni_gram(b) + number_of_2_grams_starting_with_b) --> this is to ensure sum_a(p(a|b)) = 1

Hope it helps

**Comment by manvan18** [comment]
Thanks you very much ! I know your idea  but I dont known code:
else
 log = Math.log(1.0 / (2*(size2Grams + totalcount2Grams))); //(1)
							
if(i == 1) {
								log += Math.log((double)(number1GRam + 1)/(size1Gram + totalcount1Gram)) ;  //(2)
							}

why when i == 1  we use (2)  and why do we use (1)?

**Comment by tienthanhdhcn** [comment]
It is the Markov model where p(a,b,c,d) = p(a) * p(b|a) * p(c|b) * p(d|c), if i == 1 we need to calculate p(a) using (2)

**Comment by manvan18** [comment]
Thanks you very much!
